In [3]:
import numpy as np
arr=np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [4]:
import numpy as np
arr=np.array([[12,23,34],[45,56,67]])
for x in arr:
    print(x)

[12 23 34]
[45 56 67]


In [6]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [7]:
import numpy as np
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8


In [8]:
import numpy as np
a=np.array([1,2,3])
b=3
result=a+b
print(result)

[4 5 6]


In [9]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=4
result=a+b
print(result)

[[ 5  6  7]
 [ 8  9 10]]


In [10]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=([56,67,78])
result=a+b
print(result)

[[57 69 81]
 [60 72 84]]


In [13]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [14]:
import numpy as np
x=np.array([[23,45],[55,67]])
y=np.array([[11,22],[33,44]])
result=np.concatenate((x,y),axis=0)
print(result)


[[23 45]
 [55 67]
 [11 22]
 [33 44]]


In [16]:
import numpy as np
x=np.array([1,2,3])
y=np.array([7,8,9])
result=np.stack((x,y),axis=1)
print(result)

[[1 7]
 [2 8]
 [3 9]]


In [19]:
import numpy as np
a=np.array([[2,3,1],[33,45,11]])
b=np.array([[1,2,3],[4,5,6]])
result=np.stack((a,b),axis=0)
print(result)

[[[ 2  3  1]
  [33 45 11]]

 [[ 1  2  3]
  [ 4  5  6]]]


In [20]:
import numpy as np
a=np.array([[2,3,1],[33,45,11]])
b=np.array([[1,2,3],[4,5,6]])
result=np.stack((a,b),axis=1)
print(result)

[[[ 2  3  1]
  [ 1  2  3]]

 [[33 45 11]
  [ 4  5  6]]]


In [1]:
import numpy as np
arr=np.array([1,2,3])
arr1=np.array([4,5,6])
x=np.hstack((arr,arr1))
print(x)

[1 2 3 4 5 6]


In [4]:
import numpy as np
arr=np.array([1,2,3])
arr1=np.array([4,5,6])
x=np.vstack((arr,arr1))
print(x)

[[1 2 3]
 [4 5 6]]


In [5]:
import numpy as np
arr=np.array([1,2,3])
arr1=np.array([4,5,6])
x=np.dstack((arr,arr1))
print(x)

[[[1 4]
  [2 5]
  [3 6]]]


In [8]:
import math
print(math.sqrt(8))

2.8284271247461903


In [10]:
import math
print(math.sqrt((7)))

2.6457513110645907


In [11]:
import math
print(math.sqrt((2)))
print(math.sqrt((3)))

1.4142135623730951
1.7320508075688772


In [12]:
import math
print(math.cos(2))

-0.4161468365471424


In [13]:
import math
print(math.factorial(4))

24


In [14]:
import math
print(math.exp(3))

20.085536923187668


In [16]:
import numpy as np
print(math.pow(4,8))

65536.0


In [20]:
import random
random.seed(10)
print(random.random())

0.5714025946899135


In [24]:
import random
random.seed('apple')
print(random.random())

0.340367122988108


In [32]:
import random
print(random.randrange(3,9))

5


In [34]:
import random
mylist=['appple','orange','banana']
random.shuffle(mylist)
print(mylist)


['appple', 'orange', 'banana']


In [42]:
import random
print(random.randint(3,6))

3


In [46]:
import random
print(random.random())

0.03001130322011969


In [49]:
import random
mylist=['apple','orange','kiwi']
print(random.sample(mylist,k=2))

['orange', 'kiwi']
