In [1]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr.dtype)

int64


In [4]:
arr=np.array([1.2,2.3,2.1])
print(arr.dtype)

float64


In [8]:
import numpy as np
arr=np.array([3+4j])
print(arr.dtype)

complex128


In [9]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr.dtype)

int64


In [12]:
import numpy as np
arr=np.array([1,2,3,4],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [15]:
import numpy as np
arr=np.array([1.2,3.4,3.2],dtype='i')
print(arr)
print(arr.dtype)

[1 3 3]
int32


In [16]:
import numpy as np
arr=np.array([1.2,3.4,4.2],dtype='i')
print(arr)
print(arr.dtype)

[1 3 4]
int32


In [17]:
import numpy as np
arr=np.array([1,4,3,6],dtype='f')
print(arr)
print(arr.dtype)

[1. 4. 3. 6.]
float32


In [20]:
import numpy as np
arr=np.array([1,4,3],dtype='f8')
print(arr)
print(arr.dtype)

[1. 4. 3.]
float64


In [23]:
import numpy as np
arr=np.array([1.2,3.4,5.6])
newarr=arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 3 5]
int32


In [26]:
import numpy as np
arr=np.array([1,2,3,4])
x=arr.astype('S')
print(x)
print(arr.dtype)
print(x.dtype)

[b'1' b'2' b'3' b'4']
int64
|S21


In [29]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
x=arr.astype('f')
print(x)
print(x.dtype)
print(arr.dtype)

[1. 2. 3. 4. 5. 6. 7.]
float32
int64


In [30]:
import numpy as np
arr=np.array([3,4,5,2])
print(arr.dtype)

int64


In [32]:
import numpy as np
arr=np.array([4,5,6,7],dtype='f')
print(arr)
print(arr.dtype)


[4. 5. 6. 7.]
float32


In [34]:
import numpy as np
arr=np.array([3,4,5,6])
x=arr.astype('f')
print(x)
print(x.dtype)

[3. 4. 5. 6.]
float32


In [35]:
import numpy as np
arr=np.array([2,3,4,5,6])
x=arr.copy()
arr[0]=34
print(arr)
print(x)

[34  3  4  5  6]
[2 3 4 5 6]


In [36]:
import numpy as np
arr=np.array([3.1,2.3,4.5])
x=arr.copy()
arr[2]=7.4
print(arr)
print(x)

[3.1 2.3 7.4]
[3.1 2.3 4.5]


In [43]:
import numpy as np
arr=np.array([3.4,5.6,8.9])
x=arr.copy()
arr[1]=1.2
print(arr)
print(x)


[3.4 1.2 8.9]
[3.4 5.6 8.9]


In [45]:
import numpy as np
arr=np.array([7,5,4,3])
x=arr.view()
arr[3]=21
print(arr)
print(x)

[ 7  5  4 21]
[ 7  5  4 21]


In [47]:
import numpy as np
arr=np.array([2.3,4.3,1.6])
x=arr.view()
arr[2]=7.6
print(arr)
print(x)

[2.3 4.3 7.6]
[2.3 4.3 7.6]


In [48]:
import numpy as np
arr=np.array([2.3,4.3,1.6])
x=arr.copy()
arr[2]=7.6
print(arr)
print(x)

[2.3 4.3 7.6]
[2.3 4.3 1.6]


In [49]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr.shape)

(2, 5)


In [50]:
import numpy as np
arr=np.array([[1,4,2,6,7,8,3],[7,8,9,0,4,1,5]])
print(arr.shape)

(2, 7)


In [51]:
import numpy as np
arr=np.array([[3,2],[4,6]])
print(arr.shape)

(2, 2)


In [53]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
x=arr.reshape(5,2)
print(x)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [54]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
x=arr.reshape(2,3)
print(x)

[[1 2 3]
 [4 5 6]]


In [55]:
import numpy as np
arr=np.array([3,2,1,4,5,6,7,8,9])
x=arr.reshape(3,3)
print(x)

[[3 2 1]
 [4 5 6]
 [7 8 9]]


In [56]:
import numpy as np
arr=np.array([2,3,4,5,6,7,8,9,0,21,1,7])
x=arr.reshape(2,3,2)
print(x)

[[[ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [ 0 21]
  [ 1  7]]]


In [58]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)
