In [7]:
import numpy as np
arr=np.array([1.4,2.6,3.8,4.3,5.9])
x=arr.astype('f')
print(x)
print(x.dtype)

[1.4 2.6 3.8 4.3 5.9]
float32


In [8]:
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=2
print(arr)
print(x)

[2 2 3 4 5]
[1 2 3 4 5]


In [9]:
import numpy as np
arr=np.array([1,2,3,4,56])
x=arr.view()
arr[3]=234
print(arr)
print(x)

[  1   2   3 234  56]
[  1   2   3 234  56]


In [10]:
import numpy as np
arr=np.array([[1,2,3,54,8],[7,8,9,0,4]])
print(arr.shape)

(2, 5)


In [15]:
import numpy as np
arr=np.array([2,1,3,4,5,6,7,8])
newarr=arr.reshape(4,2)
print(newarr)

[[2 1]
 [3 4]
 [5 6]
 [7 8]]


In [17]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,910,23,45,66])
x=arr.reshape(2,3,2)
print(x)

[[[  1   2]
  [  3   4]
  [  5   6]]

 [[  7   8]
  [910  23]
  [ 45  66]]]


In [24]:
import numpy as np
arr=np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [21]:
import numpy as np
arr=np.array([[2,1,3],[4,5,6]])
for x in arr:
    print(x)

[2 1 3]
[4 5 6]


In [27]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,19]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6
7
8
9
19


In [28]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [35]:
import numpy as np
arr=np.array([[[0,9,8],[7,6,5]],[[4,3,2],[1,0,10]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

0
9
8
7
6
5
4
3
2
1
0
10


In [40]:
import numpy as np
a=np.array([1,2,3])
b=5
result=a+b
print(result)

[6 7 8]


In [43]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([10,22,23])
result=(a+b)
print(result)

[[11 24 26]
 [14 27 29]]
