In [2]:
!pip install numpy


[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np
print(np. __version__)

2.1.3


In [4]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [7]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [11]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [16]:
arr=np.array([2,3,4,5],ndmin=5)
print(arr)
print('no of dimension:',arr.ndim)

[[[[[2 3 4 5]]]]]
no of dimension: 5


In [21]:
array=np.array([1,4,6,8],ndmin=3)
print(array)
print(array.ndim)

[[[1 4 6 8]]]
3


In [22]:
import numpy as np
arr=np.array([[2,3,4,5],[1,9,8,7]])
print(arr[1,1])

9


In [25]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[3,5,7]]])
print(arr[0,1,0])

4


In [26]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[3,5,7]]])
print(arr[1,1,1])

5


In [28]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[1,0:4])

[5 6 7 8]


In [29]:
import numpy as np
arr=np.array([[2,4,3,1],[5,6,7,8]])
print(arr[0,1:3])

[4 3]


In [33]:
import numpy as np
arr=np.array([[2,1,3,4,8],[7,8,9,0,5]])
print(arr[1,1:4])

[8 9 0]


In [37]:
import numpy as np
arr=np.array([[3,2,1,4,5,6],[2,3,4,6,1,7]])
print(arr[0:2,1:4])

[[2 1 4]
 [3 4 6]]
