In [2]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr.dtype)

int64


In [4]:
import numpy as np
x=np.array([1.2,3.4,5.6])
print(x.dtype)

float64


In [5]:
import numpy as np
x=np.array(['godly','mathew'])
print(x.dtype)

<U6


In [7]:
import numpy as np
x=np.array([1,2,3,4],dtype='i')
print(x.dtype)

int32


In [9]:
import numpy as np
x=np.array([2.3,1.5,3.4],dtype='S')
print(x)

[b'2.3' b'1.5' b'3.4']


In [12]:
import numpy as np
x=np.array([3+4j],dtype='S4')
print(x)

[b'(3+4']


In [25]:
import numpy as np
x=np.array([1.2,3.4,5.6])
newarr=x.astype('i')
print(newarr)
print(newarr.dtype)

[1 3 5]
int32


In [20]:
import numpy as np
x=np.array([1,2,3,4,5,6])
newarr=arr.astype('i')
# newarr=arr.astype('f')
# newarr=arr.astype('S')
print(newarr)
print(newarr.dtype)

[1 2 3 4]
int32


In [22]:
import numpy as np
arr=np.array([2,3,5,])
x=arr.copy()
arr[0]=23
print(arr)
print(x)

[23  3  5]
[2 3 5]


In [24]:
import numpy as np
x=np.array([3.4,5.6])
x1=arr.copy()
arr[1]=24
print(arr)
print(x)

[23 24  5]
[3.4 5.6]


In [27]:
import numpy as np
x=arr.view()
arr[0]=23
print(arr)
print(x)

[23 24  5]
[23 24  5]


In [30]:
import numpy as np
arr = np.array([1, 2, 3, 4])
x = arr.view() 
arr[1:3] = [23, 33]
print("arr:", arr)
print("x  :", x)


arr: [ 1 23 33  4]
x  : [ 1 23 33  4]


In [32]:
import numpy as np
x=np.array([[2,3,4,5],[1,7,6,9]])
print(x.shape)

(2, 4)


In [34]:
import numpy as np
arr=np.array([1,2,3,4,5,6,5,1,2,3,4,5])
newarr=arr.reshape(4,3)
print(newarr)

[[1 2 3]
 [4 5 6]
 [5 1 2]
 [3 4 5]]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(